name: Build Docker Image

on:
  push:
    branches:
      - add-dockerfile

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        submodules: 'recursive'

    - name: Build Docker image
      run: docker build -t firovm:$GITHUB_SHA .
